name: Postman API Integration for ESign

on:
  push:
     branches:
      - master
     paths:
      - './esignature.rest.swagger-v2.1.json'

jobs:
  upload-swagger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send Swagger Spec to Postman API ESign
      env:
        POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
      run: |
        SWAGGER_FILE="./esignature.rest.swagger-v2.1.json"
        API_ID=${{vars.ESIGN_API_ID}}
        SCHEMA_ID=${{vars.ESIGN_DEFINITION_ID}}
        FILE_PATH="index.json"
        
        CONTENT=$(jq -Rs . < ${SWAGGER_FILE})
        curl --location --request PUT "https://api.getpostman.com/apis/$API_ID/schemas/$SCHEMA_ID/files/$FILE_PATH" \
        --header "Accept: application/vnd.api.v10+json" \
        --header "Content-Type: application/json" \
        --header "X-Api-Key: $POSTMAN_API_KEY" \
        --data "{\"content\": ${CONTENT}}"